language: cpp

install:
  - gem install coveralls-lcov

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd Line_Test/tests
  - ./run_tests
  
after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
