language: cpp

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd Line_Test/tests
  - ls
  - ./run_tests
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
