language: cpp

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - make
